# Part I - (Ford GoBike System Data)
## by (Dina Alade)

## Introduction








## Preliminary Wrangling

In [1]:
#load necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#load dataset using pandas
df = pd.read_csv('201902-fordgobike-tripdata.csv')
df.head()

,duration_sec,start_time,end_time,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bike_id,user_type,member_birth_year,member_gender,bike_share_for_all_trip
0,52185,2019-02-28 17:32:10.1450,2019-03-01 08:01:55.9750,21.0,Montgomery St BART Station (Market St at 2nd St),37.789625,-122.400811,13.0,Commercial St at Montgomery St,37.794231,-122.402923,4902,Customer,1984.0,Male,No
1,42521,2019-02-28 18:53:21.7890,2019-03-01 06:42:03.0560,23.0,The Embarcadero at Steuart St,37.791464,-122.391034,81.0,Berry St at 4th St,37.775880,-122.393170,2535,Customer,NaN,NaN,No
2,61854,2019-02-28 12:13:13.2180,2019-03-01 05:24:08.1460,86.0,Market St at Dolores St,37.769305,-122.426826,3.0,Powell St BART Station (Market St at 4th St),37.786375,-122.404904,5905,Customer,1972.0,Male,No
3,36490,2019-02-28 17:54:26.0100,2019-03-01 04:02:36.8420,375.0,Grove St at Masonic Ave,37.774836,-122.446546,70.0,Central Ave at Fell St,37.773311,-122.444293,6638,Subscriber,1989.0,Other,No
4,1585,2019-02-28 23:54:18.5490,2019-03-01 00:20:44.0740,7.0,Frank H Ogawa Plaza,37.804562,-122.271738,222.0,10th Ave at E 15th St,37.792714,-122.248780,4898,Subscriber,1974.0,Male,Yes

In [3]:
#check the shape of the dataset
df.shape

(183412, 16)

In [4]:
#check the summary of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183412 entries, 0 to 183411
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   duration_sec             183412 non-null  int64
 1   start_time               183412 non-null  object
 2   end_time                 183412 non-null  object
 3   start_station_id         183215 non-null  float64
 4   start_station_name       183215 non-null  object
 5   start_station_latitude   183412 non-null  float64
 6   start_station_longitude  183412 non-null  float64
 7   end_station_id           183215 non-null  float64
 8   end_station_name         183215 non-null  object
 9   end_station_latitude     183412 non-null  float64
 10  end_station_longitude    183412 non-null  float64
 11  bike_id                  183412 non-null  int64
 12  user_type                183412 non-null  object
 13  member_birth_year        175147 non-null  float64
 14  member_gender            175147 non-null  object
 15  bike_share_for_all_trip  183412 non-null  object
dtypes: float64(7), int64(2), object(7)
memory usage: 22.4+ MB

In [5]:
#check the datasets summary statistics
df.describe()

,duration_sec,start_station_id,start_station_latitude,start_station_longitude,end_station_id,end_station_latitude,end_station_longitude,bike_id,member_birth_year
count,183412.000000,183215.000000,183412.000000,183412.000000,183215.000000,183412.000000,183412.000000,183412.000000,175147.000000
mean,726.078435,138.590427,37.771223,-122.352664,136.249123,37.771427,-122.352250,4472.906375,1984.806437
std,1794.389780,111.778864,0.099581,0.117097,111.515131,0.099490,0.116673,1664.383394,10.116689
min,61.000000,3.000000,37.317298,-122.453704,3.000000,37.317298,-122.453704,11.000000,1878.000000
25%,325.000000,47.000000,37.770083,-122.412408,44.000000,37.770407,-122.411726,3777.000000,1980.000000
50%,514.000000,104.000000,37.780760,-122.398285,100.000000,37.781010,-122.398279,4958.000000,1987.000000
75%,796.000000,239.000000,37.797280,-122.286533,235.000000,37.797320,-122.288045,5502.000000,1992.000000
max,85444.000000,398.000000,37.880222,-121.874119,398.000000,37.880222,-121.874119,6645.000000,2001.000000

In [6]:
#check for missing values
df.isna().sum()

duration_sec                  0
start_time                    0
end_time                      0
start_station_id            197
start_station_name          197
start_station_latitude        0
start_station_longitude       0
end_station_id              197
end_station_name            197
end_station_latitude          0
end_station_longitude         0
bike_id                       0
user_type                     0
member_birth_year          8265
member_gender              8265
bike_share_for_all_trip       0
dtype: int64

In [7]:
#check for the datasets data types
df.dtypes

duration_sec                 int64
start_time                  object
end_time                    object
start_station_id           float64
start_station_name          object
start_station_latitude     float64
start_station_longitude    float64
end_station_id             float64
end_station_name            object
end_station_latitude       float64
end_station_longitude      float64
bike_id                      int64
user_type                   object
member_birth_year          float64
member_gender               object
bike_share_for_all_trip     object
dtype: object

In [8]:
#check for duplicates
df.duplicated().sum()

0

#### check for unique values gender, station names and user type

In [14]:
df['member_gender'].unique()

array(['Male', nan, 'Other', 'Female'], dtype=object)

In [16]:
df['start_station_name'].nunique()

329

In [23]:
df['start_station_name'].unique()

array(['Montgomery St BART Station (Market St at 2nd St)',
       'The Embarcadero at Steuart St', 'Market St at Dolores St',
       'Grove St at Masonic Ave', 'Frank H Ogawa Plaza',
       '4th St at Mission Bay Blvd S', 'Palm St at Willow St',
       'Washington St at Kearny St', 'Post St at Kearny St',
       'Jones St at Post St',
       'Civic Center/UN Plaza BART Station (Market St at McAllister St)',
       'Valencia St at 21st St', 'Channing Way at Shattuck Ave',
       'Bancroft Way at College Ave', 'Howard St at Mary St',
       '22nd St at Dolores St', 'Laguna St at Hayes St',
       '5th St at Folsom', 'Telegraph Ave at 23rd St',
       'Page St at Scott St', 'Lake Merritt BART Station',
       'West St at 40th St', 'The Embarcadero at Sansome St',
       'Folsom St at 9th St', 'University Ave at Oxford St',
       'MLK Jr Way at University Ave', 'The Embarcadero at Bryant St',
       '17th St at Valencia St', 'Valencia St at 16th St',
       'Valencia St at 22nd St', 'Franklin Square',
       'San Pablo Ave at MLK Jr Way', '19th St at Mission St',
       'Market St at 10th St', 'Folsom St at 13th St',
       'San Francisco Ferry Building (Harry Bridges Plaza)',
       '4th St at 16th St', 'Beale St at Harrison St',
       'Broadway at Battery St', 'Cesar Chavez St at Dolores St',
       'San Fernando St at 4th St', 'Grove St at Divisadero',
       'Sanchez St at 17th St', 'Harmon St at Adeline St',
       'Mission Playground', 'Davis St at Jackson St',
       'Haste St at Telegraph Ave', 'Howard St at 8th St',
       'Folsom St at 3rd St', 'Father Alfred E Boeddeker Park',
       'Commercial St at Montgomery St', 'Hubbell St at 16th St',
       'San Francisco Public Library (Grove St at Hyde St)',
       'Bancroft Way at Telegraph Ave', '19th Street BART Station',
       '18th St at Noe St', 'Hyde St at Post St', '24th St at Market St',
       'Vine St at Shattuck Ave',
       'San Francisco Caltrain (Townsend St at 4th St)',
       'Valencia St at Clinton Park',
       'Union Square (Powell St at Post St)', 'Broderick St at Oak St',
       'San Francisco Caltrain Station 2  (Townsend St at 4th St)',
       'North Berkeley BART Station', 'Downtown Berkeley BART',
       'Fell St at Stanyan St', 'San Salvador St at 9th St',
       'Marston Campbell Park', 'Oregon St at Adeline St',
       '11th St at Natoma St', 'Harrison St at 20th St',
       'Haste St at College Ave', '24th St at Bartlett St',
       'Sanchez St at 15th St', 'Telegraph Ave at 19th St',
       'Powell St BART Station (Market St at 5th St)',
       'Jersey St at Castro St', 'Pierce St at Haight St',
       'MacArthur BART Station', 'El Embarcadero at Grand Ave',
       '23rd St at San Bruno Ave', 'Golden Gate Ave at Hyde St',
       'S Van Ness Ave at Market St', 'Jackson Playground',
       'San Fernando St at 7th St', 'West St at University Ave',
       'Myrtle St at Polk St', 'Woolsey St at Sacramento St',
       'Townsend St at 7th St', 'Harrison St at 17th St',
       'West Oakland BART Station', 'Cyril Magnin St at Ellis St',
       'Fulton St at Bancroft Way', '14th St at Mission St',
       'San Pedro Square', 'Market St at Franklin St',
       'Folsom St at 19th St', 'College Ave at Taft Ave',
       'Rhode Island St at 17th St', 'Shattuck Ave at Hearst Ave',
       'The Embarcadero at Vallejo St', 'Webster St at Grove St',
       'Raymond Kimbell Playground', 'Victoria Manalo Draves Park',
       '20th St at Bryant St', 'S Park St at 3rd St',
       'Lakeshore Ave at Trestle Glen Rd',
       'Channing Way at San Pablo Ave', 'Mission Dolores Park',
       'Lombard St at Columbus Ave', '17th St at Dolores St',
       'Precita Park', 'Central Ave at Fell St', '4th St at Harrison St',
       'Horton St at 40th St', 'Golden Gate Ave at Franklin St',
       'Embarcadero BART Station (Beale St at Market St)',
       '9th St at San Fernando St', '3rd St at Townsend St',
       'McCoppin St at Valencia St', '13th St at Franklin St',
       'Mission Bay Kids Park', 'Potrero Ave and Mariposa St',
       'Emeryville Public Market', 'Union St at 10th St',
       'Jackson St at 11th St', 'Broadway at Kearny',
       'Paseo De San Antonio at 2nd St', 'Valencia St at Cesar Chavez St',
       'Rockridge BART Station', '8th St at Brannan St',
       'College Ave at Alcatraz Ave', '16th St Mission BART Station 2',
       'San Jose Diridon Station', 'Masonic Ave at Turk St',
       '17th & Folsom Street Park (17th St at Folsom St)',
       'Grand Ave at Webster St', '7th St at Brannan St',
       'Steuart St at Market St', 'Scott St at Golden Gate Ave',
       'Parker St at Fulton St', 'Berkeley Civic Center',
       'Clay St at Battery St', '11th St at Bryant St',
       'Powell St BART Station (Market St at 4th St)',
       'Doyle St at 59th St', '34th St at Telegraph Ave', 'Esprit Park',
       'Emeryville Town Hall', 'Division St at Potrero Ave',
       'Irwin St at 8th St', 'Pierce Ave at Market St',
       'Howard St at Beale St', 'Washington St at 8th St', 'Snow Park',
       'Dolores St at 15th St', 'Hearst Ave at Euclid Ave',
       'Telegraph Ave at Ashby Ave', '8th St at Ringold St',
       '14th St at Mandela Pkwy', 'Morrison Ave at Julian St',
       'Church St at Duboce Ave', 'Townsend St at 5th St',
       'Valencia St at 24th St', '16th St at Prosper St',
       '5th St at Virginia St', "Webster St at O'Farrell St",
       'Shattuck Ave at Telegraph Ave', 'Jackson St at 5th St',
       'Berry St at 4th St', '2nd St at Townsend St',
       'Telegraph Ave at Carleton St', 'Ellsworth St at Russell St',
       'Adeline St at 40th St', 'Bay Pl at Vernon St',
       'Russell St at College Ave', '22nd St Caltrain Station',
       'Folsom St at 15th St', nan, 'Ninth St at Heinz Ave',
       '15th St at Potrero Ave', '23rd St at Tennessee St',
       'McAllister St at Baker St', 'Bryant St at 2nd St',
       'Mississippi St at 17th St', 'Ryland Park',
       'Fountain Alley at S 2nd St', 'Turk St at Fillmore St',
       'Ashby BART Station', 'Shattuck Ave at 51st St',
       'Julian St at The Alameda', '20th St at Dolores St',
       'Broadway at Coronado Ave', 'Grand Ave at Santa Clara Ave',
       'Eureka Valley Recreation Center', 'Parker Ave at McAllister St',
       'Berry St at King St',
       'Salesforce Transit Center (Natoma St at 2nd St)',
       'San Antonio Park', 'Lakeside Dr at 14th St',
       '16th St Mission BART', 'Stanford Ave at Hollis St',
       'Broadway at 40th St',
       'Mechanics Monument Plaza (Market St at Bush St)',
       'Madison St at 17th St', 'Grand Ave at Perkins St',
       'Garfield Square (25th St at Harrison St)', '53rd St at Hollis St',
       '2nd St at Julian St', 'Telegraph Ave at Alcatraz Ave',
       'San Francisco City Hall (Polk St at Grove St)',
       '5th St at Brannan St', '10th St at Fallon St',
       'Yerba Buena Center for the Arts (Howard St at 3rd St)',
       '30th St at San Jose Ave', '29th St at Tiffany Ave',
       'Webster St at 2nd St', 'Koshland Park', 'Jersey St at Church St',
       'Santa Clara St at 7th St', 'Telegraph Ave at 58th St',
       'Fruitvale BART Station', 'Addison St at Fourth St',
       'Leavenworth St at Broadway', 'Telegraph Ave at 27th St',
       'Potrero del Sol Park (25th St at Utah St)',
       'Spear St at Folsom St', 'College Ave at Harwood Ave',
       "O'Farrell St at Divisadero St", '1st St at Folsom St',
       'Bryant St at 15th St', 'Golden Gate Ave at Polk St',
       '5th St at San Salvador St', '29th St at Church St',
       'Alamo Square (Steiner St at Fulton St)',
       'Autumn Parkway at Coleman Ave', 'Fulton St at Ashby Ave',
       'Howard St at 2nd St', '19th St at Florida St',
       'Market St at 45th St', 'Derby St at College Ave',
       'Market St at Brockhurst St', 'California St at University Ave',
       'MLK Jr Way at 14th St', 'Market St at 40th St',
       'Julian St at 6th St', 'Cahill Park', 'San Jose City Hall',
       'Virginia St at Shattuck Ave', 'Jack London Square',
       'Milvia St at Derby St', 'Webster St at 19th St',
       '24th St at Chattanooga St', 'The Alameda at Bush St',
       '49th St at Telegraph Ave', 'Broadway at 30th St',
       'Bryant St at 6th St', 'Empire St at 1st St',
       'China Basin St at 3rd St', '47th St at San Pablo Ave',
       'San Salvador St at 1st St', '45th St at Manila',
       'San Carlos St at Market St', 'San Pablo Ave at 27th St',
       'Market St at Park St', 'Franklin St at 9th St',
       'Almaden Blvd at San Fernando St', 'Oak St at 1st St',
       'William St at 10th St', 'Isabella St at San Pablo Ave',
       'Guerrero Park', '10th St at University Ave', 'DeFremery Park',
       'Fifth St at Delaware St', 'Williams Ave at 3rd St',
       '4th Ave at E 12th St (Temporary Location)',
       'Shattuck Ave at 55th St', '59th St at Horton St', 'SAP Center',
       '37th St at West St', 'Almaden Blvd at Balbach St',
       '65th St at Hollis St', 'Santa Clara St at Almaden Blvd',
       'Ninth St at Parker St', 'Bushrod Park', 'Empire St at 7th St',
       'Mendell St at Fairfax Ave', '16th St Depot',
       'Newhall St at 3rd St', 'George St at 1st St',
       'Mission St at 1st St', 'Duboce Park', 'Locust St at Grant St',
       '32nd St at Adeline St', 'Mosswood Park',
       'Delmas Ave and San Fernando St', 'Lane St at Revere Ave',
       '2nd Ave at E 18th St', 'San Carlos St at 11th St',
       'Williams Ave at Apollo St', 'MacArthur Blvd at Telegraph Ave',
       'Bestor Art Park', 'College Ave at Bryant Ave',
       'Miles Ave at Cavour St', 'Saint James Park',
       '14th St at Filbert St', 'Foothill Blvd at Fruitvale Ave',
       'Market St at 8th St', 'Backesto Park (Jackson St at 13th St)',
       '10th Ave at E 15th St', 'Alcatraz Ave at Shattuck Ave',
       '55th St at Telegraph Ave', 'Genoa St at 55th St',
       'Dover St at 57th St', 'San Pablo Park',
       '6th Ave at E 12th St (Temporary Location)', 'Taylor St at 9th St',
       '27th St at MLK Jr Way', 'Foothill Blvd at Harrington Ave',
       '23rd Ave at Foothill Blvd', 'San Pedro St at Hedding St',
       '45th St at MLK Jr Way', '5th St at Taylor St',
       'Foothill Blvd at 42nd Ave', 'Willow St at Vine St',
       '26th Ave at International Blvd', 'Farnam St at Fruitvale Ave',
       '21st Ave at International Blvd', '2nd St at Folsom St'],
      dtype=object)

In [18]:
df['end_station_name'].nunique()

329

In [22]:
df['end_station_name'].unique()

array(['Commercial St at Montgomery St', 'Berry St at 4th St',
       'Powell St BART Station (Market St at 4th St)',
       'Central Ave at Fell St', '10th Ave at E 15th St',
       'Broadway at Kearny', 'San Jose Diridon Station',
       'Valencia St at 21st St', 'Mission Playground',
       'San Francisco Public Library (Grove St at Hyde St)',
       'Bryant St at 2nd St', 'Shattuck Ave at Hearst Ave',
       'Channing Way at Shattuck Ave', '8th St at Ringold St',
       'Broderick St at Oak St', 'Potrero Ave and Mariposa St',
       'Market St at Franklin St', 'Telegraph Ave at 23rd St',
       '17th St at Dolores St',
       '6th Ave at E 12th St (Temporary Location)',
       'McAllister St at Baker St', 'Telegraph Ave at Carleton St',
       'Genoa St at 55th St', 'Grand Ave at Perkins St',
       'San Francisco Ferry Building (Harry Bridges Plaza)',
       'Folsom St at 9th St', 'Channing Way at San Pablo Ave',
       '2nd St at Townsend St', 'Pierce St at Haight St',
       'Potrero del Sol Park (25th St at Utah St)',
       'Valencia St at 22nd St', 'Jackson Playground',
       'Dolores St at 15th St', '29th St at Church St',
       '19th St at Mission St', 'Bay Pl at Vernon St',
       'Post St at Kearny St',
       'Yerba Buena Center for the Arts (Howard St at 3rd St)',
       '4th St at Mission Bay Blvd S', 'Father Alfred E Boeddeker Park',
       'Market St at 10th St', '24th St at Chattanooga St',
       'Pierce Ave at Market St', 'Fell St at Stanyan St',
       '17th St at Valencia St', 'San Pablo Ave at 27th St',
       'Howard St at Mary St', 'Davis St at Jackson St',
       'Victoria Manalo Draves Park', 'Jersey St at Church St',
       'Haste St at Telegraph Ave', 'Eureka Valley Recreation Center',
       'Washington St at Kearny St', 'Grove St at Divisadero',
       'Parker St at Fulton St', 'El Embarcadero at Grand Ave',
       'Lake Merritt BART Station', 'Hyde St at Post St',
       '24th St at Market St', '5th St at Brannan St',
       '24th St at Bartlett St', 'Townsend St at 5th St',
       'Addison St at Fourth St', 'Broadway at Battery St',
       'Market St at Dolores St', '5th St at Virginia St',
       'Marston Campbell Park', 'University Ave at Oxford St',
       'Valencia St at 24th St', 'Valencia St at Cesar Chavez St',
       'Ryland Park', 'Precita Park', 'Derby St at College Ave',
       'Jersey St at Castro St', '11th St at Natoma St',
       '45th St at MLK Jr Way', 'Valencia St at 16th St',
       'San Francisco Caltrain Station 2  (Townsend St at 4th St)',
       'Montgomery St BART Station (Market St at 2nd St)',
       '18th St at Noe St', '37th St at West St', 'Newhall St at 3rd St',
       'Haste St at College Ave', 'Cyril Magnin St at Ellis St',
       'Beale St at Harrison St', 'Fulton St at Bancroft Way',
       'San Fernando St at 4th St',
       'Garfield Square (25th St at Harrison St)',
       '29th St at Tiffany Ave', 'Bancroft Way at College Ave',
       'Ashby BART Station', '11th St at Bryant St',
       '14th St at Mandela Pkwy', 'Howard St at 8th St',
       'Leavenworth St at Broadway', 'Locust St at Grant St',
       'Lombard St at Columbus Ave', 'Sanchez St at 17th St',
       '45th St at Manila', '23rd St at San Bruno Ave',
       'Morrison Ave at Julian St', 'Sanchez St at 15th St',
       'Koshland Park', 'Harrison St at 20th St', '2nd Ave at E 18th St',
       'Steuart St at Market St', 'Church St at Duboce Ave',
       'Page St at Scott St', 'Bancroft Way at Telegraph Ave',
       'Mission Bay Kids Park', 'Folsom St at 3rd St',
       'Valencia St at Clinton Park', 'Grand Ave at Santa Clara Ave',
       '19th Street BART Station', 'Folsom St at 19th St',
       'West Oakland BART Station', 'S Park St at 3rd St',
       '5th St at Folsom',
       'Embarcadero BART Station (Beale St at Market St)',
       'Howard St at 2nd St', 'The Embarcadero at Sansome St',
       'Backesto Park (Jackson St at 13th St)', 'Esprit Park',
       'Myrtle St at Polk St', 'Franklin Square', 'Empire St at 7th St',
       'Lakeside Dr at 14th St', 'Laguna St at Hayes St',
       '65th St at Hollis St', '4th St at 16th St',
       '49th St at Telegraph Ave', '16th St Mission BART Station 2',
       'Lane St at Revere Ave', 'MLK Jr Way at University Ave',
       '2nd St at Julian St', 'Webster St at Grove St',
       'Telegraph Ave at Ashby Ave', 'Bryant St at 6th St',
       '20th St at Dolores St',
       'Powell St BART Station (Market St at 5th St)',
       'San Francisco Caltrain (Townsend St at 4th St)',
       '8th St at Brannan St', 'Shattuck Ave at Telegraph Ave',
       'Downtown Berkeley BART', 'North Berkeley BART Station',
       'Turk St at Fillmore St', 'Woolsey St at Sacramento St',
       '4th St at Harrison St', 'The Embarcadero at Bryant St',
       "O'Farrell St at Divisadero St", 'Grove St at Masonic Ave',
       'Hubbell St at 16th St',
       'Civic Center/UN Plaza BART Station (Market St at McAllister St)',
       '3rd St at Townsend St', 'Fountain Alley at S 2nd St',
       'China Basin St at 3rd St', '59th St at Horton St',
       'Mission Dolores Park', 'San Carlos St at 11th St',
       'Jackson St at 11th St', '22nd St Caltrain Station',
       'Townsend St at 7th St', '7th St at Brannan St',
       'Webster St at 2nd St', 'Ellsworth St at Russell St',
       "Webster St at O'Farrell St", 'Harmon St at Adeline St',
       '1st St at Folsom St', 'Vine St at Shattuck Ave',
       'Stanford Ave at Hollis St', 'Jones St at Post St',
       'West St at University Ave', 'Paseo De San Antonio at 2nd St',
       'Duboce Park', 'The Embarcadero at Steuart St',
       'Russell St at College Ave', 'Golden Gate Ave at Hyde St',
       'Berkeley Civic Center', '47th St at San Pablo Ave',
       'George St at 1st St', '53rd St at Hollis St',
       'West St at 40th St', '15th St at Potrero Ave',
       'Division St at Potrero Ave', 'San Pablo Ave at MLK Jr Way',
       'Jackson St at 5th St', 'Union Square (Powell St at Post St)',
       '4th Ave at E 12th St (Temporary Location)', 'Bushrod Park',
       'Rhode Island St at 17th St', 'Folsom St at 13th St',
       'Virginia St at Shattuck Ave', '16th St Mission BART',
       'Lakeshore Ave at Trestle Glen Rd', 'Masonic Ave at Turk St', nan,
       'Harrison St at 17th St', 'McCoppin St at Valencia St',
       '17th & Folsom Street Park (17th St at Folsom St)',
       '10th St at Fallon St', '34th St at Telegraph Ave',
       'The Alameda at Bush St', '9th St at San Fernando St',
       '20th St at Bryant St', 'Howard St at Beale St',
       'Cesar Chavez St at Dolores St', '55th St at Telegraph Ave',
       'S Van Ness Ave at Market St', 'Scott St at Golden Gate Ave',
       '14th St at Mission St', 'Mississippi St at 17th St',
       'Alamo Square (Steiner St at Fulton St)',
       'Shattuck Ave at 51st St', 'MacArthur BART Station',
       'Madison St at 17th St', 'Horton St at 40th St',
       'Hearst Ave at Euclid Ave', 'Folsom St at 15th St',
       '19th St at Florida St', 'Alcatraz Ave at Shattuck Ave',
       'San Fernando St at 7th St', 'MLK Jr Way at 14th St',
       'Milvia St at Derby St', 'College Ave at Alcatraz Ave',
       'Washington St at 8th St', 'Guerrero Park',
       'Oregon St at Adeline St', 'Parker Ave at McAllister St',
       '23rd St at Tennessee St', 'Clay St at Battery St',
       'Broadway at 40th St',
       'Salesforce Transit Center (Natoma St at 2nd St)',
       'Telegraph Ave at 19th St', 'Emeryville Public Market',
       'Golden Gate Ave at Polk St', 'Telegraph Ave at 58th St',
       'Foothill Blvd at Harrington Ave', 'The Embarcadero at Vallejo St',
       '16th St at Prosper St', 'Berry St at King St',
       'Broadway at Coronado Ave', 'Market St at 45th St',
       'Mechanics Monument Plaza (Market St at Bush St)',
       'Dover St at 57th St', 'Miles Ave at Cavour St',
       'Rockridge BART Station', 'Fifth St at Delaware St',
       'College Ave at Harwood Ave', 'California St at University Ave',
       'Union St at 10th St', '5th St at San Salvador St',
       'Mosswood Park', 'William St at 10th St', '5th St at Taylor St',
       'Julian St at The Alameda', 'Irwin St at 8th St',
       'Market St at Brockhurst St', 'Adeline St at 40th St',
       '30th St at San Jose Ave', 'Spear St at Folsom St',
       '27th St at MLK Jr Way',
       'San Francisco City Hall (Polk St at Grove St)',
       '22nd St at Dolores St', 'Frank H Ogawa Plaza',
       'Shattuck Ave at 55th St', 'Golden Gate Ave at Franklin St',
       'Broadway at 30th St', 'Bryant St at 15th St',
       'Grand Ave at Webster St', 'Julian St at 6th St',
       'Santa Clara St at 7th St', '14th St at Filbert St',
       'Emeryville Town Hall', 'Cahill Park',
       'Raymond Kimbell Playground', 'Autumn Parkway at Coleman Ave',
       'Isabella St at San Pablo Ave', 'San Salvador St at 9th St',
       'Telegraph Ave at 27th St', '13th St at Franklin St',
       'Doyle St at 59th St', 'Jack London Square', 'SAP Center',
       'Telegraph Ave at Alcatraz Ave', 'San Carlos St at Market St',
       '10th St at University Ave', 'Ninth St at Heinz Ave',
       'Market St at 40th St', '23rd Ave at Foothill Blvd',
       'Bestor Art Park', '32nd St at Adeline St', 'DeFremery Park',
       'San Pedro Square', 'San Salvador St at 1st St',
       'Fulton St at Ashby Ave', 'Ninth St at Parker St',
       'Taylor St at 9th St', 'Empire St at 1st St',
       'Franklin St at 9th St', 'Webster St at 19th St', 'San Pablo Park',
       'College Ave at Taft Ave', 'Market St at 8th St', 'Snow Park',
       'San Antonio Park', 'San Jose City Hall',
       'Delmas Ave and San Fernando St', 'Mendell St at Fairfax Ave',
       'Santa Clara St at Almaden Blvd', 'College Ave at Bryant Ave',
       'Foothill Blvd at Fruitvale Ave', 'Palm St at Willow St',
       'Saint James Park', 'Williams Ave at 3rd St',
       'Market St at Park St', 'Almaden Blvd at Balbach St',
       'Almaden Blvd at San Fernando St', 'Foothill Blvd at 42nd Ave',
       'Fruitvale BART Station', 'MacArthur Blvd at Telegraph Ave',
       'Williams Ave at Apollo St', 'Mission St at 1st St',
       'San Pedro St at Hedding St', 'Oak St at 1st St',
       'Farnam St at Fruitvale Ave', '26th Ave at International Blvd',
       '16th St Depot', '21st Ave at International Blvd',
       'Willow St at Vine St', '2nd St at Folsom St'], dtype=object)

In [20]:
df['user_type'].nunique()

2

In [24]:
df['user_type'].unique()

array(['Customer', 'Subscriber'], dtype=object)

Brief summary of assessment done

- The dataset has 183412 rows and 16 columns
- Since the time column is in the wrong datatype, it will be changed to datetime
- Null values will be fixed
- There are no duplicates in the dataset
- There are 329 stations used in the dataset


## Cleaning

In [25]:
#change start and end time to datetime 
df['start_time'] = pd.to_datetime(df.start_time)
df['end_time'] = pd.to_datetime(df.end_time)

In [26]:
#check for change
df.dtypes

duration_sec                        int64
start_time                 datetime64[ns]
end_time                   datetime64[ns]
start_station_id                  float64
start_station_name                 object
start_station_latitude            float64
start_station_longitude           float64
end_station_id                    float64
end_station_name                   object
end_station_latitude              float64
end_station_longitude             float64
bike_id                             int64
user_type                          object
member_birth_year                 float64
member_gender                      object
bike_share_for_all_trip            object
dtype: object

In [27]:
#change bike id to string
df['bike_id'] = df['bike_id'].astype('object')

In [29]:
df.dtypes

duration_sec                        int64
start_time                 datetime64[ns]
end_time                   datetime64[ns]
start_station_id                  float64
start_station_name                 object
start_station_latitude            float64
start_station_longitude           float64
end_station_id                    float64
end_station_name                   object
end_station_latitude              float64
end_station_longitude             float64
bike_id                            object
user_type                          object
member_birth_year                 float64
member_gender                      object
bike_share_for_all_trip            object
dtype: object

In [30]:
#check bike share for all trips unique values
df['bike_share_for_all_trip'].unique()

array(['No', 'Yes'], dtype=object)

### What is the structure of the dataset
> The dataset has 183412 rows and 16 columns, with both numerical and categorical features.
    > The categorical columns have the following labels
        > User type - Subscriber and Customer
        > Member Gender - Male, Female and Other
        > Bike Share - Yes or No



### What is/are the main feature(s) of interest in your dataset?
> The Start time column to determine the best time bikes are rented



### What features in the dataset do you think will help support your investigation into your feature(s) of interest?
> 1. The End time column to determine the duration of bike rental
> 2. Start and End Station names to know which stations have the most activity
> 3. Bike id to know the most used bikes and time used
> 4. User Type to know which type of users rent bikes the most
> 5. Member Gender to know the gender that use bikes often
> 6. Bike share for all trip